services:
  - docker

env:
  global:
    - DOCKER_REPO="oanhnn/gh-pages"

before_script:
  - docker info
  - if [[ ${TRAVIS_BRANCH} == "master" ]]; then
      export IMAGE_TAG="latest";
    else
      export IMAGE_TAG=${TRAVIS_BRANCH};
    fi
  - export IMAGE_NAME="${DOCKER_REPO}:${IMAGE_TAG}"

script:
  - ./hooks/build
