version: "3"

services:
  pages:
    image: oanhnn/gh-pages:test
    command: ["bundle", "exec", "jekyll", "serve", "-H", "0.0.0.0", "-P", "4000", "--watch", "--draft"]
    ports:
      - 4000:4000
    restart: unless-stopped
    volumes:
      - .:/src/site
